version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "dailypush"
    labels:
      - "dependencies"
      - "go"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
