services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - POLLING_INTERVAL=5s
      - STATS_SOURCE=json
      - JSON_STATS_DIRECTORY=/json_stats
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    volumes:
      - ./json:/json_stats:ro
  redis:
    image: "redis:6.2-alpine"
    volumes:
      - redis-data:/data
volumes:
  redis-data: