services:
  api:
    build:
      context: .
      target: production-runtime
    ports:
      - "8080:8080"
      - "2345:2345"
    depends_on:
      - redis
    environment:
      - POLLING_INTERVAL=5s
      - STATS_SOURCE=json
      - JSON_STATS_DIRECTORY=/json_stats
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    volumes:
      - ./json:/json_stats:ro
    command: dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient --log main.go
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
  redis:
    image: "redis:6.2-alpine"
    volumes:
      - redis-data:/data
volumes:
  redis-data: