version: '3.9'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - POLLING_INTERVAL=5m # Set the desired polling interval here
      - STATS_SOURCE=json
      - JSON_STATS_DIRECTORY=./json_stats
  redis:
    image: "redis:6.2-alpine"
    volumes:
      - redis-data:/data

  website:
    build: ./path/to/website
    ports:
      - "80:80"

volumes:
  redis-data:
